### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by jlrickert** [jlrickert/knutjs#15]
Add linting to the project.

- Verify if project is properly formatted using prettier rules
- Verify coding style. This is something that needs to be defined
- Enforce rules using GitHub CI/CD pipeline

  Should not be able to publish new version if lint rules are violated. Should not be able to merge a PR to main if lint rules are violated.

  Example that may work in the Verify workflow

  ```yaml
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint code
        run: pnpm run lint
  ```
